use_frameworks!

target 'SwiftBerry_Example' do
  pod 'SwiftBerry', :path => '../'

  target 'SwiftBerry_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
